BMLT Basic Standalone Satellite: bmlt_basic Class Reference
bmlt_basic Class Reference
Public Member Functions
output_head ($in_shortcode= '[[bmlt]]')
Outputs the head HTML, CSS and JavaScript. *.
output_body ()
Outputs the body HTML and JavaScript. *.
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
standard_head ($in_text=null)
returns any necessary head content. *
admin_head ()
No admin in this implementation. * *.
admin_page ()
Prevents the admin page from being shown. *.
Public Attributes
$my_shortcode = null
This will hold the given shortcode.
Protected Member Functions
get_ajax_base_uri ()
Return an HTTP path to the AJAX callback target. * *.
get_plugin_path ()
Return an HTTP path to the plugin directory. * *.
geDefaultBMLTOptions ()
This gets the default admin options from the object (not the DB). * *.
cms_get_option ($in_option_key)
This gets the admin options from the config file. * *.
cms_get_page_settings_id ($in_text, $in_check_mobile=false)
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
get_admin_ajax_base_uri ()
We don't do admin in this variant, so this makes that clear. * *.
get_admin_form_uri ()
We don't do admin in this variant, so this makes that clear. * *.
cms_set_option ($in_option_key, $in_option_value)
You cannot set options in this implementation. * *.
cms_delete_option ($in_option_key)
You cannot delete options in this implementation. * *.
cms_get_post_meta ($in_page_id, $in_settings_id)
This is declared to make it clear that we don't do post meta. * *.
Detailed Description
Definition at line 49 of file bmlt_basic.class.php.
Member Function Documentation
admin_head ()
No admin in this implementation. * *.
Returns
null *
Definition at line 423 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
cms_delete_option ($in_option_key) protected
You cannot delete options in this implementation. * *.
Returns
false *
Parameters
$in_option_key The name of the option
Definition at line 396 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return false;
     }
cms_get_option ($in_option_key) protected
This gets the admin options from the config file. * *.
Returns
an associative array, with the option settings. *
Parameters
$in_option_key The name of the option
Definition at line 174 of file bmlt_basic.class.php.
References $bmlt_basic_configuration.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $bmlt_basic_configuration;
         global $bmlt_basic_configuration_index;
         $ret = null;
         if ($in_option_key != self::$admin2OptionsName) {
             $index = intval(max($bmlt_basic_configuration_index - 1, intval(str_replace(self::$adminOptionsName.'_', '', $in_option_key))));
             $ret = $bmlt_basic_configuration[$index];
         } else {
             $ret = array ( 'num_servers' => $bmlt_basic_configuration_index );
         }
         return $ret;
     }
cms_get_page_settings_id ($in_text, $in_check_mobile = false) protected
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
Returns
a mixed type, with the settings ID. *
Parameters
$in_text Required (for the base version) content to check.
$in_check_mobile True if this includes a check for mobile. Default is false.
Definition at line 203 of file bmlt_basic.class.php.
Referenced by standard_head().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $my_option_id = 0;
         if (!$in_check_mobile && isset($this->my_http_vars['bmlt_settings_id']) && is_array($this->getBMLTOptions($this->my_http_vars['bmlt_settings_id']))) {
             $my_option_id = $this->my_http_vars['bmlt_settings_id'];
         } else {
             $support_mobile = self::get_shortcode($in_text, 'bmlt_mobile');
             if ($support_mobile === true) {
                 $options = $this->getBMLTOptions(1);
                 $support_mobile = strval($options['id']);
             }
             if ($in_check_mobile && $support_mobile && !isset($this->my_http_vars['BMLTPlugin_mobile']) && (self::mobile_sniff_ua($this->my_http_vars) != 'xhtml')) {
                 $my_option_id = $support_mobile;
             } elseif (!$in_check_mobile) {
                 if (isset($this->my_http_vars['bmlt_settings_id']) && intval($this->my_http_vars['bmlt_settings_id'])) {
                     $my_option_id = intval($this->my_http_vars['bmlt_settings_id']);
                 } elseif ($in_text) {
                     $my_option_id_content = parent::cms_get_page_settings_id($in_text, $in_check_mobile);
                     $my_option_id = $my_option_id_content ? $my_option_id_content : $my_option_id;
                 }
                 if (!$my_option_id) {   // If nothing else gives, we go for the default (first) settings.
                     $options = $this->getBMLTOptions(1);
                     $my_option_id = $options['id'];
                 }
             }
         }
         return $my_option_id;
     }
cms_get_post_meta ($in_page_id, $in_settings_id) protected
This is declared to make it clear that we don't do post meta. * *.
Returns
null *
Parameters
$in_page_id The ID of the page/post
$in_settings_id The ID of the meta tag to fetch
Definition at line 409 of file bmlt_basic.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
cms_set_option ($in_option_key, $in_option_value) protected
You cannot set options in this implementation. * *.
Returns
false *
Parameters
$in_option_key The name of the option
$in_option_value the values to be set (associative array)
Definition at line 382 of file bmlt_basic.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return false;
     }
geDefaultBMLTOptions () protected
This gets the default admin options from the object (not the DB). * *.
Returns
an associative array, with the default option settings. *
Definition at line 160 of file bmlt_basic.class.php.
References $bmlt_basic_configuration.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $bmlt_basic_configuration;
         // These are the defaults. If the saved option has a different value, it replaces the ones in here.
         return $bmlt_basic_configuration[0];
     }
get_admin_ajax_base_uri () protected
We don't do admin in this variant, so this makes that clear. * *.
THESE ARE ALL DISABLED IN THE BASIC SATELLITE *
Returns
null *
Definition at line 358 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
get_admin_form_uri () protected
We don't do admin in this variant, so this makes that clear. * *.
Returns
null *
Definition at line 370 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
get_ajax_base_uri () protected
Return an HTTP path to the AJAX callback target. * *.
INTERNAL FUNCTIONS (NOT CALLED BY CLIENT) *
Returns
a string, containing the path. *
Definition at line 91 of file bmlt_basic.class.php.
Referenced by get_plugin_path().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // We try to account for SSL and unusual TCP ports.
         $port = null;
         $https = false;
         $from_proxy = array_key_exists("HTTP_X_FORWARDED_PROTO", $_SERVER);
         if ($from_proxy) {
             // If the port is specified in the header, use it. If not, default to 80
             // for http and 443 for https. We can't trust what's in $_SERVER['SERVER_PORT']
             // because something in front of the server is fielding the request.
             $https = $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https';
             if (array_key_exists("HTTP_X_FORWARDED_PORT", $_SERVER)) {
                 $port = intval($_SERVER['HTTP_X_FORWARDED_PORT']);
             } elseif ($https) {
                 $port = 443;
             } else {
                 $port = 80;
             }
         } else {
             $port = $_SERVER['SERVER_PORT'];
             // IIS puts "off" in the HTTPS field, so we need to test for that.
             $https = (!empty($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] !== 'off') || ($port == 443)));
         }
         $server_path = $_SERVER['SERVER_NAME'];
         $my_path = $_SERVER['PHP_SELF'];
         $server_path .= trim((($https && ($port != 443)) || (!$https && ($port != 80))) ? ':'.$port : '', '/');
         $server_path = 'http'.($https ? 's' : '').'://'.$server_path.$my_path;
         return $server_path;
     }
get_plugin_path () protected
Return an HTTP path to the plugin directory. * *.
Returns
a string, containing the path. *
Definition at line 128 of file bmlt_basic.class.php.
References get_ajax_base_uri().
Referenced by standard_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = isset($this->my_http_vars['base_url']) ? $this->my_http_vars['base_url'] : dirname($this->get_ajax_base_uri()).'/bmlt-basic/vendor/bmlt/bmlt-satellite-base-class/';
         return $ret;
     }
output_head ($in_shortcode = '[[bmlt]]')
Outputs the head HTML, CSS and JavaScript. *.
CLIENT FUNCTIONS *
Parameters
$in_shortcode You need to provide a shortcode, if you want something other than the default.
Definition at line 63 of file bmlt_basic.class.php.
References standard_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->my_shortcode = $in_shortcode;  // Save this.
         echo $this->standard_head($this->my_shortcode);
     }
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
Returns
a string, processed by WP. *
Parameters
$in_string The string to be processed.
Definition at line 145 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $in_string = htmlspecialchars($in_string);
         return $in_string;
     }
standard_head ($in_text = null)
returns any necessary head content. *
Parameters
$in_text This is the page content text.
Definition at line 245 of file bmlt_basic.class.php.
References cms_get_page_settings_id(), and get_plugin_path().
Referenced by output_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->ajax_router();
         $load_head = false;   // This is a throwback. It prevents the GM JS from being loaded if there is no directly specified settings ID.
         $head_content = "<!-- Added by the BMLT plugin 3.X. -->\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" /><meta http-equiv=\"Content-Style-Type\" content=\"text/css\" /><meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />";
         $support_mobile = $this->cms_get_page_settings_id($in_text, true);
         if ($support_mobile) {
             $mobile_options = $this->getBMLTOptions_by_id($support_mobile);
         } else {
             $support_mobile = null;
         }
         $options = $this->getBMLTOptions_by_id($this->cms_get_page_settings_id($in_text));
         if ($support_mobile && is_array($mobile_options) && count($mobile_options)) {
             $mobile_url = $_SERVER['PHP_SELF'].'?BMLTPlugin_mobile&bmlt_settings_id='.$support_mobile;
             if (isset($this->my_http_vars['WML'])) {
                 $mobile_url .= '&WML='.intval($this->my_http_vars['WML']);
             }
             if (isset($this->my_http_vars['simulate_smartphone'])) {
                 $mobile_url .= '&simulate_smartphone';
             }
             if (ob_get_contents()) {
                 ob_end_clean();
             }
             header("location: $mobile_url");
             die();
         }
         $load_server_header = $this->get_shortcode($in_text, 'bmlt');
         $this->my_http_vars['start_view'] = $options['bmlt_initial_view'];
         $this->load_params();
         $root_server_root = $options['root_server'];
         $head_content .= '<meta name="BMLT-Root-URI" content="'.htmlspecialchars($root_server_root).'" />';
         $head_content .= "\n".'<style type="text/css">'."\n";
         $temp = self::stripFile("styles.css", $options['theme']);
         if ($temp) {
             $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
             $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
             $head_content .= "\t$temp\n";
         }
         $temp = self::stripFile("nouveau_map_styles.css", $options['theme']);
         if ($temp) {
             $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
             $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
             $head_content .= "\t$temp\n";
         }
         $head_content .= self::stripFile('table_styles.css') . "\n";
         $head_content .= self::stripFile('quicksearch.css') . "\n";
         $dirname = ROOTPATH . '/vendor/bmlt/bmlt-satellite-base-class/themes';
         $dir = new DirectoryIterator($dirname);
         foreach ($dir as $fileinfo) {
             if (!$fileinfo->isDot()) {
                 $fName = $fileinfo->getFilename();
                 $temp = self::stripFile("table_styles.css", $fName);
                 if ($temp) {
                     $image_dir_path = $this->get_plugin_path() . '/themes/' . $fName . '/images/';
                     $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
                     $head_content .= "\t$temp\n";
                 }
                 $temp = self::stripFile("quicksearch.css", $fName);
                 if ($temp) {
                     $head_content .= "\t$temp\n";
                 }
             }
         }
         $head_content .= self::stripFile('responsiveness.css') . "\n";
         $head_content .= "\n</style>\n";
         $head_content .= '<script type="text/javascript">';
         $head_content .= self::stripFile('javascript.js');
         if ($this->get_shortcode($in_text, 'bmlt_quicksearch')) {
             $head_content .= self::stripFile('quicksearch.js') . (defined('_DEBUG_MODE_') ? "\n" : '');
         }
         if ($this->get_shortcode($in_text, 'bmlt_map')) {
             $head_content .= self::stripFile('map_search.js');
         }
         if ($this->get_shortcode($in_text, 'bmlt_mobile')) {
             $head_content .= self::stripFile('fast_mobile_lookup.js');
         }
         $head_content .= '</script>';
         return $head_content;
     }
The documentation for this class was generated from the following file:
/home/travis/build/bmlt-enabled/bmlt-basic/bmlt-basic/bmlt_basic.class.php